import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "../providers/ClientProviders";
import Header from "@/components/Header";
import LeftSideBar from "@/components/LeftSideBar";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            <Toaster />
            <div className="flex">
              <LeftSideBar />
              <main className="flex-1 bg-background">{children}</main>
            </div>
          </ThemeProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
